enabled_plugins:
    backends:
    services:
    views:

views:
    displays:
        default_display:
            -
                title: Firstname
                default: Unknown
                field: firstname
            -
                title: Lastname
                default: Unknown
                field: lastname
            -
                title: Number
                default:
                field: number
    profile_to_display:
        default: default_display

services:
    lookup:
        default:
            sources:
                - my_csv

rest_api:
       listen: 0.0.0.0
       port: 9489
