enabled_plugins:
    backends:
        - csv
    services:
        - lookup
    views:
        - default_json

views:
    displays:
        default_display:
            -
                title: Firstname
                default: Unknown
                field: firstname
            -
                title: Lastname
                default: Unknown
                field: lastname
            -
                title: Number
                default:
                field: number
    profile_to_display:
        default: default_display

services:
    lookup:
        default:
            sources:
                - my_csv
                - second_csv
                - third_csv
